"""Linky component constants."""
from pylinky.abstractauth import AUTHORIZE_URL_SANDBOX, ENDPOINT_TOKEN_URL_SANDBOX

DOMAIN = "linky"

OAUTH2_AUTHORIZE = AUTHORIZE_URL_SANDBOX
OAUTH2_TOKEN = ENDPOINT_TOKEN_URL_SANDBOX
